AWSTemplateFormatVersion: '2010-09-09'
Description: 'Concert Data Platform - Data Storage and Processing Infrastructure (S3, Redshift, Glue, Kinesis)'

Parameters:
  Environment:
    Type: String
    Default: development
    AllowedValues:
      - development
      - staging
      - production
    Description: Environment name
  
  NetworkStackName:
    Type: String
    Description: Name of the networking stack for imports
  
  RedshiftMasterUsername:
    Type: String
    Default: admin
    Description: Master username for Redshift
  
  RedshiftMasterPassword:
    Type: String
    NoEcho: true
    MinLength: 8
    Description: Master password for Redshift (min 8 chars)
  
  RedshiftNodeType:
    Type: String
    Default: ra3.xlplus
    AllowedValues:
      - ra3.xlplus
      - ra3.4xlarge
      - dc2.large
    Description: Redshift node type

Resources:
  # S3 Buckets
  
  # Raw Data Bucket
  RawDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'concert-data-raw-${Environment}-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
              - TransitionInDays: 90
                StorageClass: GLACIER
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 90
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub 'concert-data-raw-${Environment}'
        - Key: Environment
          Value: !Ref Environment
        - Key: DataClassification
          Value: Raw

  # Processed Data Bucket
  ProcessedDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'concert-data-processed-${Environment}-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - TransitionInDays: 60
                StorageClass: STANDARD_IA
              - TransitionInDays: 180
                StorageClass: GLACIER
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub 'concert-data-processed-${Environment}'
        - Key: Environment
          Value: !Ref Environment
        - Key: DataClassification
          Value: Processed

  # Model Artifacts Bucket
  ModelArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'concert-model-artifacts-${Environment}-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub 'concert-model-artifacts-${Environment}'
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: MLModels

  # Lambda Deployment Bucket
  LambdaDeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'concert-lambda-deployment-${Environment}-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 7
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub 'concert-lambda-deployment-${Environment}'
        - Key: Environment
          Value: !Ref Environment

  # Kinesis Data Streams
  
  # Concert Events Stream
  ConcertEventsStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: !Sub 'concert-events-stream-${Environment}'
      ShardCount: 2
      RetentionPeriodHours: 24
      StreamEncryption:
        EncryptionType: KMS
        KeyId: alias/aws/kinesis
      Tags:
        - Key: Name
          Value: !Sub 'concert-events-stream-${Environment}'
        - Key: Environment
          Value: !Ref Environment

  # Artist Data Stream
  ArtistDataStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: !Sub 'concert-artist-stream-${Environment}'
      ShardCount: 1
      RetentionPeriodHours: 24
      StreamEncryption:
        EncryptionType: KMS
        KeyId: alias/aws/kinesis
      Tags:
        - Key: Name
          Value: !Sub 'concert-artist-stream-${Environment}'
        - Key: Environment
          Value: !Ref Environment

  # Venue Data Stream
  VenueDataStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: !Sub 'concert-venue-stream-${Environment}'
      ShardCount: 1
      RetentionPeriodHours: 24
      StreamEncryption:
        EncryptionType: KMS
        KeyId: alias/aws/kinesis
      Tags:
        - Key: Name
          Value: !Sub 'concert-venue-stream-${Environment}'
        - Key: Environment
          Value: !Ref Environment

  # AWS Glue Resources
  
  # Glue Database
  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Sub 'concert_data_${Environment}'
        Description: Concert data catalog database
        LocationUri: !Sub 's3://${ProcessedDataBucket}/'

  # Glue IAM Role
  GlueServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'ConcertGlueServiceRole-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource:
                  - !Sub '${RawDataBucket.Arn}/*'
                  - !Sub '${ProcessedDataBucket.Arn}/*'
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource:
                  - !GetAtt RawDataBucket.Arn
                  - !GetAtt ProcessedDataBucket.Arn
      Tags:
        - Key: Name
          Value: !Sub 'ConcertGlueServiceRole-${Environment}'
        - Key: Environment
          Value: !Ref Environment

  # Redshift Serverless Resources
  
  # Redshift IAM Role
  RedshiftServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'ConcertRedshiftServiceRole-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: redshift.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      Policies:
        - PolicyName: GlueAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - glue:GetDatabase
                  - glue:GetTable
                  - glue:GetPartitions
                Resource: '*'
      Tags:
        - Key: Name
          Value: !Sub 'ConcertRedshiftServiceRole-${Environment}'
        - Key: Environment
          Value: !Ref Environment

  # Redshift Subnet Group
  RedshiftSubnetGroup:
    Type: AWS::Redshift::ClusterSubnetGroup
    Properties:
      Description: Subnet group for Concert Redshift cluster
      SubnetIds:
        - Fn::ImportValue: !Sub '${NetworkStackName}-PublicSubnet1Id'
        - Fn::ImportValue: !Sub '${NetworkStackName}-PublicSubnet2Id'
      Tags:
        - Key: Name
          Value: !Sub 'concert-redshift-subnet-group-${Environment}'
        - Key: Environment
          Value: !Ref Environment

  # Redshift Serverless Namespace
  RedshiftNamespace:
    Type: AWS::RedshiftServerless::Namespace
    Properties:
      NamespaceName: !Sub 'concert-namespace-${Environment}'
      DbName: concerts
      AdminUsername: !Ref RedshiftMasterUsername
      AdminUserPassword: !Ref RedshiftMasterPassword
      IamRoles:
        - !GetAtt RedshiftServiceRole.Arn
      DefaultIamRoleArn: !GetAtt RedshiftServiceRole.Arn
      Tags:
        - Key: Name
          Value: !Sub 'concert-namespace-${Environment}'
        - Key: Environment
          Value: !Ref Environment

  # Redshift Serverless Workgroup
  RedshiftWorkgroup:
    Type: AWS::RedshiftServerless::Workgroup
    Properties:
      WorkgroupName: !Sub 'concert-workgroup-${Environment}'
      NamespaceName: !Ref RedshiftNamespace
      BaseCapacity: 32
      PubliclyAccessible: true
      SubnetIds:
        - Fn::ImportValue: !Sub '${NetworkStackName}-PublicSubnet1Id'
        - Fn::ImportValue: !Sub '${NetworkStackName}-PublicSubnet2Id'
      SecurityGroupIds:
        - Fn::ImportValue: !Sub '${NetworkStackName}-RedshiftSecurityGroupId'
      Tags:
        - Key: Name
          Value: !Sub 'concert-workgroup-${Environment}'
        - Key: Environment
          Value: !Ref Environment

  # S3 Bucket Policies
  
  RawDataBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref RawDataBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowGlueAccess
            Effect: Allow
            Principal:
              AWS: !GetAtt GlueServiceRole.Arn
            Action:
              - s3:GetObject
              - s3:PutObject
            Resource: !Sub '${RawDataBucket.Arn}/*'
          - Sid: AllowRedshiftAccess
            Effect: Allow
            Principal:
              AWS: !GetAtt RedshiftServiceRole.Arn
            Action:
              - s3:GetObject
              - s3:ListBucket
            Resource:
              - !GetAtt RawDataBucket.Arn
              - !Sub '${RawDataBucket.Arn}/*'

  ProcessedDataBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ProcessedDataBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowGlueAccess
            Effect: Allow
            Principal:
              AWS: !GetAtt GlueServiceRole.Arn
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
            Resource: !Sub '${ProcessedDataBucket.Arn}/*'
          - Sid: AllowRedshiftAccess
            Effect: Allow
            Principal:
              AWS: !GetAtt RedshiftServiceRole.Arn
            Action:
              - s3:GetObject
              - s3:ListBucket
            Resource:
              - !GetAtt ProcessedDataBucket.Arn
              - !Sub '${ProcessedDataBucket.Arn}/*'

Outputs:
  RawDataBucketName:
    Description: Raw data S3 bucket name
    Value: !Ref RawDataBucket
    Export:
      Name: !Sub '${AWS::StackName}-RawDataBucket'

  ProcessedDataBucketName:
    Description: Processed data S3 bucket name
    Value: !Ref ProcessedDataBucket
    Export:
      Name: !Sub '${AWS::StackName}-ProcessedDataBucket'

  ModelArtifactsBucketName:
    Description: Model artifacts S3 bucket name
    Value: !Ref ModelArtifactsBucket
    Export:
      Name: !Sub '${AWS::StackName}-ModelArtifactsBucket'

  LambdaDeploymentBucketName:
    Description: Lambda deployment S3 bucket name
    Value: !Ref LambdaDeploymentBucket
    Export:
      Name: !Sub '${AWS::StackName}-LambdaDeploymentBucket'

  ConcertEventsStreamName:
    Description: Concert events Kinesis stream name
    Value: !Ref ConcertEventsStream
    Export:
      Name: !Sub '${AWS::StackName}-ConcertEventsStream'

  ArtistDataStreamName:
    Description: Artist data Kinesis stream name
    Value: !Ref ArtistDataStream
    Export:
      Name: !Sub '${AWS::StackName}-ArtistDataStream'

  VenueDataStreamName:
    Description: Venue data Kinesis stream name
    Value: !Ref VenueDataStream
    Export:
      Name: !Sub '${AWS::StackName}-VenueDataStream'

  GlueDatabaseName:
    Description: Glue database name
    Value: !Ref GlueDatabase
    Export:
      Name: !Sub '${AWS::StackName}-GlueDatabase'

  GlueServiceRoleArn:
    Description: Glue service role ARN
    Value: !GetAtt GlueServiceRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-GlueServiceRoleArn'

  RedshiftNamespaceName:
    Description: Redshift Serverless namespace name
    Value: !Ref RedshiftNamespace
    Export:
      Name: !Sub '${AWS::StackName}-RedshiftNamespace'

  RedshiftWorkgroupName:
    Description: Redshift Serverless workgroup name
    Value: !Ref RedshiftWorkgroup
    Export:
      Name: !Sub '${AWS::StackName}-RedshiftWorkgroup'

  RedshiftServiceRoleArn:
    Description: Redshift service role ARN
    Value: !GetAtt RedshiftServiceRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-RedshiftServiceRoleArn'
